### ISSUE TITLE
Instructions need additional step (at https://discord.com/channels/403278800273801227/1258510942304469153/1258532757911633983)

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/auctionator-app-bugs#2]
**Describe the bug**
At https://discord.com/channels/403278800273801227/1258510942304469153/1258532757911633983)](https://discord.com/channels/403278800273801227/1258510942304469153/1258532757911633983) the instructions need an additional step to Update the Installation Path.

I'd suggest that the "Installation Path" label be "World of Warcraft Installation Path".

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 24

**Additional context**

**Logs**
Please attach the most recent logs (you can find these in your user data directory)

**Comment by jrob8577** [comment]
Thank you for the name change suggestion! I think instead of adding to the discord instructions, I should probably add something to the application instead. In my current dev copy, once users are logged in, they are forced to the settings page until a path is selected. With the name change, do you think this is sufficient guidance for a first time user?

**Comment by b-morgan** [comment]
> With the name change, do you think this is sufficient guidance for a first time user?

Probably. 

I suspect that the Discord instructions are temporary but adding a line there might be a good short term fix.

**Comment by jrob8577** [comment]
Updated discord instructions, name change in app coming in 1.0.25.
